---
- hosts: hosts
  become: true
  gather_facts: true
  tasks:
    - name: Download script
      ansible.builtin.shell: wget https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect
      ignore_errors: yes

    - name: Add execute
      ansible.builtin.shell: chmod +x nixos-infect

    - name: Install curl
      ansible.builtin.package:
        name: curl
        state: present

    - name: Delete nix
      ansible.builtin.shell: rm -rf /nix

    - name: Install nix
      become: false
      ansible.builtin.shell: curl -L https://nixos.org/nix/install | sh

    - name: Add nix's sh to bashrc
      become: false
      ansible.builtin.shell: echo "source /home/debian/.nix-profile/etc/profile.d/nix.sh" >> /home/debian/.bashrc
